name: Eleventy Build


on:
  push:
    branches:
      - master
  workflow_dispatch:
  
      
jobs:
  job1:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
          fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install unrar p7zip
        run: sudo apt-get install -y unrar p7zip
      - name: Install dependencies
        run: |
          npm install glob
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install pyrogram TgCrypto PyGithub internetarchive patool kaitaistruct
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Set games without ia
        run: |
          WOID="$(node scripts/gameswoid.js)"
          if [ -n "$WOID" ]; then
            echo "::set-output name=gameswoid::$WOID"
          fi
        id: gameswoid
      - name: Doing the job
        if: steps.gameswoid.outputs.gameswoid
        env:
          API_ID: ${{ secrets.API_ID }}
          API_HASH: ${{ secrets.API_HASH }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          ARCHIVEORG: ${{ secrets.ARCHIVEORG }}
        run: |
          echo "a${{ steps.gameswoid.outputs.gameswoid }}b"
          cp ${{ github.workspace }}/scripts/opgarchiveorg ./
          cp ${{ github.workspace }}/scripts/iso9660.py ./
          for word in ${{ steps.gameswoid.outputs.gameswoid }}; do ./opgarchiveorg $word; done
      - name: Commit files
        if: steps.gameswoid.outputs.gameswoid
        run: |
          git config --local user.email "alihardanc@gmail.com"
          git config --local user.name "alihardan"
          git fetch
          git merge
          for word in ${{ steps.gameswoid.outputs.gameswoid }}; do echo ${{ github.workspace }}/src/games/$word/; git add ${{ github.workspace }}/src/games/$word/; done
          git commit -m "opgarchiveorg ${{ steps.gameswoid.outputs.gameswoid }}"
      - name: Push changes
        if: steps.gameswoid.outputs.gameswoid
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
      - run: echo "üçè This job's status is ${{ job.status }}."
  deploy:
    runs-on: ubuntu-latest
    needs: job1
    steps:
        - uses: actions/checkout@v2

        - name: Setup Node
          uses: actions/setup-node@v2
          with:
            node-version: '14'


        - run: npm install


        - run: npm run build


        - name: Deploy
          uses: peaceiris/actions-gh-pages@v3
          with:
            deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
            publish_dir: ./dist
